spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 10
      acks: 1
    properties:
      spring.json.add.type.headers: false
eventbus:
  kafka:
    producer:
      topic: iot_pipeline_data
logging:
  level:
    ROOT: INFO
    reactor.kafka: DEBUG
server:
  port: 8082